export const FARM_HITBOXES = [
  {
    id: "house",
    label: "Dom",
    action: "open_profile",
    x: 240,
    y: 140,
    width: 260,
    height: 160,
  },
  {
    id: "barn",
    label: "Stodoła",
    action: "open_animals",
    x: 820,
    y: 130,
    width: 300,
    height: 180,
  },
  {
    id: "orchard",
    label: "Sad",
    action: "open_orchard",
    x: 600,
    y: 380,
    width: 420,
    height: 130,
  },
  {
    id: "beehive",
    label: "Ule",
    action: "open_beehive",
    x: 1180,
    y: 390,
    width: 160,
    height: 110,
  },
  {
    id: "fields",
    label: "Pola",
    action: "open_fields",
    x: 560,
    y: 610,
    width: 520,
    height: 200,
  },
  {
    id: "bike",
    label: "Miasto",
    action: "go_to_city",
    x: 170,
    y: 520,
    width: 180,
    height: 140,
  },
];
