export const FARM_HITBOXES = [
  {
    id: "house",
    label: "Dom",
    action: "open_profile",
    x: 145,
    y: 75,
    width: 380,
    height: 250,
  },
  {
    id: "barn",
    label: "Stodoła",
    action: "open_animals",
    x: 720,
    y: 35,
    width: 500,
    height: 320,
  },
  {
    id: "orchard",
    label: "Sad",
    action: "open_orchard",
    x: 525,
    y: 325,
    width: 520,
    height: 190,
  },
  {
    id: "beehive",
    label: "Ule",
    action: "open_beehive",
    x: 1160,
    y: 380,
    width: 180,
    height: 160,
  },
  {
    id: "fields",
    label: "Pola",
    action: "open_fields",
    x: 435,
    y: 500,
    width: 760,
    height: 330,
  },
  {
    id: "bike",
    label: "Miasto",
    action: "go_to_city",
    x: 95,
    y: 470,
    width: 230,
    height: 190,
  },
];
