import type { Crop } from "../types/crop";

export const CROPS: Crop[] = [
  {
    id: "test_nasiono",
    name: "Test Nasiono",
    unlockLevel: 1,
    growthTimeMs: 50_000,
    yieldAmount: 2,
    expReward: 1,
    spritePath: "/uprawy/carrot_icon_transparent.png",
  },
  {
    id: "carrot",
    name: "Marchew",
    unlockLevel: 1,
    growthTimeMs: 15 * 60_000,
    yieldAmount: 2,
    expReward: 6,
    spritePath: "/uprawy/carrot_icon_transparent.png",
    epicSpritePath: "/uprawy/carrot_epic.png",
    rottenSpritePath: "/uprawy/carrot_rotten.png",
    legendarySpritePath: "/uprawy/carrot_legendary.png",
  },
  {
    id: "potato",
    name: "Ziemniak",
    unlockLevel: 2,
    growthTimeMs: 20 * 60_000,
    yieldAmount: 2,
    expReward: 8,
    spritePath: "/uprawy/potato.png",
    epicSpritePath: "/uprawy/potato_epic.png",
    rottenSpritePath: "/uprawy/potato_rotten.png",
    legendarySpritePath: "/uprawy/potato_legendary.png",
  },
  {
    id: "tomato",
    name: "Pomidor",
    unlockLevel: 3,
    growthTimeMs: 25 * 60_000,
    yieldAmount: 2,
    expReward: 10,
    spritePath: "/uprawy/tomato.png",
    epicSpritePath: "/uprawy/tomato_epic.png",
    rottenSpritePath: "/uprawy/tomato_rotten.png",
    legendarySpritePath: "/uprawy/tomato_legendary.png",
  },
  {
    id: "cucumber",
    name: "Ogórek",
    unlockLevel: 4,
    growthTimeMs: 35 * 60_000,
    yieldAmount: 2,
    expReward: 14,
    spritePath: "/uprawy/cucumber.png",
    epicSpritePath: "/uprawy/cucumber_epic.png",
    rottenSpritePath: "/uprawy/cucumber_rotten.png",
    legendarySpritePath: "/uprawy/cucumber_legendary.png",
  },
  {
    id: "onion",
    name: "Cebula",
    unlockLevel: 5,
    growthTimeMs: 50 * 60_000,
    yieldAmount: 2,
    expReward: 20,
    spritePath: "/uprawy/onion.png",
    epicSpritePath: "/uprawy/onion_epic.png",
    rottenSpritePath: "/uprawy/onion_rotten.png",
    legendarySpritePath: "/uprawy/onion_legendary.png",
  },
  {
    id: "garlic",
    name: "Czosnek",
    unlockLevel: 6,
    growthTimeMs: 70 * 60_000,
    yieldAmount: 2,
    expReward: 28,
    spritePath: "/uprawy/garlic.png",
    epicSpritePath: "/uprawy/garlic_epic.png",
    rottenSpritePath: "/uprawy/garlic_rotten.png",
    legendarySpritePath: "/uprawy/garlic_legendary.png",
  },
  {
    id: "lettuce",
    name: "Sałata",
    unlockLevel: 7,
    growthTimeMs: 90 * 60_000,
    yieldAmount: 3,
    expReward: 36,
    spritePath: "/uprawy/lettuce.png",
    epicSpritePath: "/uprawy/lettuce_epic.png",
    rottenSpritePath: "/uprawy/lettuce_rotten.png",
    legendarySpritePath: "/uprawy/lettuce_legendary.png",
  },
  {
    id: "radish",
    name: "Rzodkiewka",
    unlockLevel: 8,
    growthTimeMs: 120 * 60_000,
    yieldAmount: 3,
    expReward: 48,
    spritePath: "/uprawy/radish.png",
    epicSpritePath: "/uprawy/radish_epic.png",
    rottenSpritePath: "/uprawy/radish_rotten.png",
    legendarySpritePath: "/uprawy/radish_legendary.png",
  },
  {
    id: "beet",
    name: "Burak",
    unlockLevel: 9,
    growthTimeMs: 160 * 60_000,
    yieldAmount: 3,
    expReward: 64,
    spritePath: "/uprawy/beet.png",
    epicSpritePath: "/uprawy/beet_epic.png",
    rottenSpritePath: "/uprawy/beet_rotten.png",
    legendarySpritePath: "/uprawy/beet_legendary.png",
  },
  {
    id: "pepper",
    name: "Papryka",
    unlockLevel: 10,
    growthTimeMs: 210 * 60_000,
    yieldAmount: 3,
    expReward: 84,
    spritePath: "/uprawy/pepper.png",
    epicSpritePath: "/uprawy/pepper_epic.png",
    rottenSpritePath: "/uprawy/pepper_rotten.png",
    legendarySpritePath: "/uprawy/pepper_legendary.png",
  },
  {
    id: "cabbage",
    name: "Kapusta",
    unlockLevel: 11,
    growthTimeMs: 275 * 60_000,
    yieldAmount: 3,
    expReward: 110,
    spritePath: "/uprawy/cabbage.png",
    epicSpritePath: "/uprawy/cabbage_epic.png",
    rottenSpritePath: "/uprawy/cabbage_rotten.png",
    legendarySpritePath: "/uprawy/cabbage_legendary.png",
  },
  {
    id: "broccoli",
    name: "Brokuł",
    unlockLevel: 12,
    growthTimeMs: 360 * 60_000,
    yieldAmount: 3,
    expReward: 144,
    spritePath: "/uprawy/broccoli.png",
    epicSpritePath: "/uprawy/broccoli_epic.png",
    rottenSpritePath: "/uprawy/broccoli_rotten.png",
    legendarySpritePath: "/uprawy/broccoli_legendary.png",
  },
  {
    id: "cauliflower",
    name: "Kalafior",
    unlockLevel: 13,
    growthTimeMs: 475 * 60_000,
    yieldAmount: 3,
    expReward: 190,
    spritePath: "/uprawy/cauliflower.png",
    epicSpritePath: "/uprawy/cauliflower_epic.png",
    rottenSpritePath: "/uprawy/cauliflower_rotten.png",
    legendarySpritePath: "/uprawy/cauliflower_legendary.png",
  },
  {
    id: "strawberry",
    name: "Truskawka",
    unlockLevel: 14,
    growthTimeMs: 625 * 60_000,
    yieldAmount: 3,
    expReward: 250,
    spritePath: "/uprawy/strawberry.png",
    epicSpritePath: "/uprawy/strawberry_epic.png",
    rottenSpritePath: "/uprawy/strawberry_rotten.png",
    legendarySpritePath: "/uprawy/strawberry_legendary.png",
  },
  {
    id: "raspberry",
    name: "Malina",
    unlockLevel: 15,
    growthTimeMs: 825 * 60_000,
    yieldAmount: 3,
    expReward: 330,
    spritePath: "/uprawy/raspberry.png",
    epicSpritePath: "/uprawy/raspberry_epic.png",
    rottenSpritePath: "/uprawy/raspberry_rotten.png",
    legendarySpritePath: "/uprawy/raspberry_legendary.png",
  },
  {
    id: "blueberry",
    name: "Borówka",
    unlockLevel: 16,
    growthTimeMs: 1075 * 60_000,
    yieldAmount: 3,
    expReward: 430,
    spritePath: "/uprawy/blueberry.png",
    epicSpritePath: "/uprawy/blueberry_epic.png",
    rottenSpritePath: "/uprawy/blueberry_rotten.png",
    legendarySpritePath: "/uprawy/blueberry_legendary.png",
  },
  {
    id: "eggplant",
    name: "Bakłażan",
    unlockLevel: 17,
    growthTimeMs: 1400 * 60_000,
    yieldAmount: 3,
    expReward: 560,
    spritePath: "/uprawy/eggplant.png",
    epicSpritePath: "/uprawy/eggplant_epic.png",
    rottenSpritePath: "/uprawy/eggplant_rotten.png",
    legendarySpritePath: "/uprawy/eggplant_legendary.png",
  },
  {
    id: "zucchini",
    name: "Cukinia",
    unlockLevel: 18,
    growthTimeMs: 1800 * 60_000,
    yieldAmount: 3,
    expReward: 720,
    spritePath: "/uprawy/zucchini.png",
    epicSpritePath: "/uprawy/zucchini_epic.png",
    rottenSpritePath: "/uprawy/zucchini_rotten.png",
    legendarySpritePath: "/uprawy/zucchini_legendary.png",
  },
  {
    id: "watermelon",
    name: "Arbuz",
    unlockLevel: 19,
    growthTimeMs: 2175 * 60_000,
    yieldAmount: 3,
    expReward: 870,
    spritePath: "/uprawy/watermelon.png",
    epicSpritePath: "/uprawy/watermelon_epic.png",
    rottenSpritePath: "/uprawy/watermelon_rotten.png",
    legendarySpritePath: "/uprawy/watermelon_legendary.png",
  },
  {
    id: "grape",
    name: "Winogrono",
    unlockLevel: 20,
    growthTimeMs: 2500 * 60_000,
    yieldAmount: 3,
    expReward: 1000,
    spritePath: "/uprawy/grape.png",
    epicSpritePath: "/uprawy/grape_epic.png",
    rottenSpritePath: "/uprawy/grape_rotten.png",
    legendarySpritePath: "/uprawy/grape_legendary.png",
  },
  {
    id: "pumpkin",
    name: "Dynia",
    unlockLevel: 21,
    growthTimeMs: 2700 * 60_000,
    yieldAmount: 3,
    expReward: 1080,
    spritePath: "/uprawy/pumpkin.png",
    epicSpritePath: "/uprawy/pumpkin_epic.png",
    rottenSpritePath: "/uprawy/pumpkin_rotten.png",
    legendarySpritePath: "/uprawy/pumpkin_legendary.png",
  },
  {
    id: "rapeseed",
    name: "Rzepak",
    unlockLevel: 22,
    growthTimeMs: 2900 * 60_000,
    yieldAmount: 3,
    expReward: 1150,
    spritePath: "/uprawy/rapeseed.png",
    epicSpritePath: "/uprawy/rapeseed_epic.png",
    rottenSpritePath: "/uprawy/rapeseed_rotten.png",
    legendarySpritePath: "/uprawy/rapeseed_legendary.png",
  },
  {
    id: "sunflower",
    name: "Słonecznik",
    unlockLevel: 23,
    growthTimeMs: 3100 * 60_000,
    yieldAmount: 3,
    expReward: 1240,
    spritePath: "/uprawy/sunflower.png",
    epicSpritePath: "/uprawy/sunflower_epic.png",
    rottenSpritePath: "/uprawy/sunflower_rotten.png",
    legendarySpritePath: "/uprawy/sunflower_legendary.png",
  },
  {
    id: "chili",
    name: "Papryczka chili",
    unlockLevel: 24,
    growthTimeMs: 3300 * 60_000,
    yieldAmount: 3,
    expReward: 1320,
    spritePath: "/uprawy/chili.png",
    epicSpritePath: "/uprawy/chili_epic.png",
    rottenSpritePath: "/uprawy/chili_rotten.png",
    legendarySpritePath: "/uprawy/chili_legendary.png",
  },
  {
    id: "asparagus",
    name: "Szparagi",
    unlockLevel: 25,
    growthTimeMs: 3600 * 60_000,
    yieldAmount: 3,
    expReward: 1440,
    spritePath: "/uprawy/asparagus.png",
    epicSpritePath: "/uprawy/asparagus_epic.png",
    rottenSpritePath: "/uprawy/asparagus_rotten.png",
    legendarySpritePath: "/uprawy/asparagus_legendary.png",
  },
];
